name: Doc Generation

on: push

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    container:
      image: "python:3"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
      - name: Install Requirments
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
