# Publish all Transforms in this Repo Production Environment
name: Publish Transforms

# Run this job each time something is committed to remote 'main' branch
on:
  push:
    branches:
      - main

jobs:
  publish-transforms:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    container:
      image: "python:3.7"

    env:
      PYTHONPATH: /__w/RasgoTransforms/RasgoTransforms
      RASGO_COMMUNITY_API_KEY: ${{ secrets.RASGO_COMMUNITY_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Python Requirments
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Publish Transforms on Prod
        run: python python/publish_transforms.py "$RASGO_COMMUNITY_API_KEY" -d production
